apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: k8s-service-demo
spec:
   replicas: 3
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: k8s-service-demo
      spec:
         containers:
         -  name: k8s-service-demo
            image: gcr.io/k8s-service-demo/kube-orchestration:0.0.2
            ports:
            -  containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
   name: k8s-service-demo
   labels:
      name: k8s-service-demo
spec:
   ports:
   -  port: 8080
      targetPort: 8080
      protocol: TCP
   selector:
      app: k8s-service-demo
   type: LoadBalancer