apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: k8s-service-demo-0.0.1
spec:
   replicas: 3
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 0
         maxSurge: 1
   template:
      metadata:
         labels:
            app: k8s-service-demo
            version: 0.0.1
      spec:
         containers:
         -  name: k8s-service-demo
            image: gcr.io/k8s-service-demo/kube-orchestration:0.0.1
            ports:
            -  containerPort: 8080
            readinessProbe:
               httpGet:
                  path: /demo
                  port: 8080
               initialDelaySeconds: 5
               periodSeconds: 5