apiVersion: v1
kind: Service
metadata:
   name: k8s-service-demo
   labels:
      name: k8s-service-demo
spec:
   ports:
   -  port: 8080
      targetPort: 8080
      protocol: TCP
   selector:
      app: k8s-service-demo
   type: LoadBalancer